import React from "react";
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ConnectButton } from "web3uikit"

function Navbar() {

    return (
        <div>
            <Head>
                <title>NFT MarketPlace</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Navbar Part */}

            <Link href="/" replace>
                Home
            </Link>
            <br></br>

            <Link href="/nftmarketplace" replace>
                NFT MarketPlace
            </Link>
            <br></br>

            <Link href="/mintnft" replace>
                Mint an NFT
            </Link>
            <br></br>

            <div className="ConnectButton">
                <ConnectButton moralisAuth={false}/>
            </div>

        </div>

    )
}
export default Navbar;

